---
- name: Confluence Playbook
  hosts: confluence
  become: true

  vars_files:
    secrets.yml

  vars:
    db_name: "confluence"
    db_user: "confluence"
    db_pass: "{{ db_pass_confluence }}"
    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "confluence.atlassian.rhel.lab"
        root: "/var/www/confluence.atlassian.rhel.lab"
        index: "index.php index.html index.htm"

        access_log: "/var/log/nginx/access.log"
        error_log: "/var/log/nginx/error.log"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "nginx_proxy.conf"
        extra_parameters: |
          location / {
            proxy_pass http://127.0.0.1:8090/confluence;
            proxy_set_header    Host            $host;
            proxy_set_header    X-Real-IP       $remote_addr;
            proxy_redirect      off;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
          }
          location /synchrony {
            client_max_body_size 100m;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://localhost:8091/synchrony;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
          }
          ssl_certificate     /etc/pki/tls/certs/confluence-certificate.pem;
          ssl_certificate_key /etc/pki/tls/certs/confluence-certificate-prv.key;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;


  pre_tasks:
    - name: Copy private cert from lab support
      ansible.builtin.get_url:
        url: http://labsupport.atlassian.rhel.lab/root-ca/confluence-certificate-prv.key
        dest: /etc/pki/tls/certs
        mode: '0440'

    - name: Copy public cert from lab support
      ansible.builtin.get_url:
        url: http://labsupport.atlassian.rhel.lab/root-ca/confluence-certificate.pem
        dest: /etc/pki/tls/certs
        mode: '0440'

  roles:
    - java
    - database
    - confluence
    - nginx_proxy
