---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        secret_ca_passphrase: completelybogus
verifier:
  name: ansible
